#!/bin/sh
#
# test whether binary files differ (per-byte compare)
#
# J.J. Green 2014

. equal-pre-compare.sh

if [ `cmp $dump_src $dump_ref | wc -l` -eq '0' ]
then
    echo 'true'
else
    echo 'false'
fi

