/* not autogenerated! */

#ifndef CPTPARSE_H
#define CPTPARSE_H

typedef int YYSTYPE;

#define yystype YYSTYPE
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL  1

#define YYLEX_PARAM   scanner
#define YYPARSE_PARAM scanner



#endif





